export const AFFILIATE_LINKS: Record<string, string> = {
  clickup: 'https://clickup.com',
  monday: 'https://monday.com',
  notion: 'https://notion.so',
  coda: 'https://coda.io',
  hubspot: 'https://hubspot.com',
  salesforce: 'https://salesforce.com',
  asana: 'https://asana.com',
  trello: 'https://trello.com',
  ahrefs: 'https://ahrefs.com',
  semrush: 'https://semrush.com',
  slack: 'https://slack.com',
  teams: 'https://teams.microsoft.com',
  shopify: 'https://shopify.com',
  woocommerce: 'https://woocommerce.com',
  zapier: 'https://zapier.com',
  make: 'https://make.com',
  webflow: 'https://webflow.com',
  framer: 'https://framer.com',
  mailchimp: 'https://mailchimp.com',
  activecampaign: 'https://activecampaign.com',
};
